/* 页面本地化配置：所有界面文案集中维护，不依赖远程翻译服务。 */
window.APP_CONFIG = {
  locale: 'zh-CN',
  appName: 'NecroSmith 2',
  categoryOrder: [
    { key: 'Skeleton', label: '骷髅' },
    { key: 'Zombie', label: '僵尸' },
    { key: 'Orc', label: '兽人' },
    { key: 'Orc Skeleton', label: '兽人骷髅' },
    { key: 'Mantis', label: '螳螂人' },
    { key: 'Cyclops', label: '独眼巨人' },
    { key: 'Lizard', label: '蜥蜴人' },
    { key: 'Harpy', label: '鹰身女妖' },
    { key: 'Fairy', label: '妖精' },
    { key: 'Mummy', label: '木乃伊' },
    { key: 'Swamp Spirit', label: '沼泽精灵' },
    { key: 'Illithid', label: '夺心魔' },
    { key: 'Cursed Armor', label: '诅咒铠甲' },
    { key: 'Demon', label: '恶魔' },
    { key: 'Treant', label: '树人' },
    { key: 'Werewolf', label: '狼人' },
    { key: 'Jotunn', label: '霜巨人' },
    { key: 'Angel', label: '天使' },
    { key: 'Steel Golem', label: '钢铁魔像' },
    { key: 'Xenostalker', label: '异星潜猎者' },
    { key: 'Draconid', label: '龙人' },
    { key: 'Earth Elemental', label: '土元素' },
    { key: 'Fire Elemental', label: '火元素' },
    { key: 'Vampire', label: '吸血鬼' },
    { key: 'Mechanoid', label: '机械体' },
    { key: 'Xenohorror', label: '异形恐魔' },
    { key: 'Cybersaurus', label: '赛博恐龙' }
  ],
  labels: {
    eyebrow: '亡灵工坊 · 配方档案',
    title: '秘方图鉴',
    subtitle: '浏览、筛选并查阅全部已收录的造物配方。',
    search: '搜索配方、部件或分类',
    searchHint: '输入中文或英文名称',
    category: '全部分类',
    craftable: '全部状态',
    craftableOnly: '可制作',
    unavailable: '暂不可制作',
    showing: '当前显示',
    total: '条配方',
    pageSize: '每页',
    rows: '条',
    firstPage: '首页',
    previousPage: '上一页',
    nextPage: '下一页',
    lastPage: '末页',
    page: '第',
    of: '页，共',
    records: '条',
    number: '序号',
    group: '造物分类',
    recipe: '配方名称',
    status: '制作状态',
    head: '头部',
    body: '身体',
    leftArm: '左手',
    rightArm: '右手',
    leftLeg: '左腿',
    rightLeg: '右腿',
    detail: '配方详情',
    close: '关闭详情',
    emptyTitle: '没有找到匹配的配方',
    emptyBody: '试试更短的关键词，或调整造物分类。',
    clearFilters: '清除筛选',
    allRecipes: '全部配方',
    recipesCollected: '收录配方',
    categories: '造物分类',
    craftableCount: '可制作配方',
    sourceLabel: '本地档案',
    sourceValue: '397 条配方 · 离线可用',
    parts: '造物部件',
    englishName: '英文名称',
    copyName: '复制配方名称',
    copied: '已复制',
    noCopy: '复制失败，请手动选择名称',
    filters: '筛选结果'
  }
};
